### ISSUE TITLE
log'sorted

### ISSUE THREAD

**Issue by Paul101432** [loki4j/loki-logback-appender#22]
I hope the log will be sorted in the same way as before after Loki restarts

PS:
+ logback.xml 

```
<sortByTime>true</sortByTime>
```

+ loki.yml

```
auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h      
  max_chunk_age: 1h           
  chunk_target_size: 1048576  
  chunk_retain_period: 30s   
  max_transfer_retries: 0    
schema_config:
  configs:
  - from: 2020-11-11
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h
storage_config:
  boltdb:
    directory: E:\server\loki\boltdb_index
  filesystem:
    directory: E:\server\loki\filesystem_chunks
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
```

+ Grafana

![image](https://user-images.githubusercontent.com/12791233/99038901-4b77f280-25c1-11eb-84aa-eae6872f099d.png)
